modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/Mari023/ae2-level-keeper/issues"
license = "MIT"

[[mods]]
modId = "level_keeper"
version = "${version}"
displayName = "ae2 Level Keeper"
authors = "Mari_023"
description = '''
Ads a Level Keeper, and a level keeping Terminal
'''
#logoFile = ""

[[dependencies.level_keeper]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.level_keeper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.level_keeper]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.level_keeper]]
modId = "appliedenergistics2"
mandatory = true
versionRange = "8.4.0"
ordering = "AFTER"
side = "BOTH"